### ISSUE TITLE
Creator crashing 

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#16]
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at PTC_Creator.Models.StatusModel.AddLog(String message, CreationStatus creationStatus, LogType type) in F:\Dropbox\VS Projects\PTC-Creator\PTC-Creator\Models\GlobalSettings.cs:line 303
   at PTC_Creator.Models.Creation.PendingChecker.GetFirstPage() in F:\Dropbox\VS Projects\PTC-Creator\PTC-Creator\Models\Creation\PendingChecker.cs:line 69
   at PTC_Creator.Models.Creation.PendingChecker.Check() in F:\Dropbox\VS Projects\PTC-Creator\PTC-Creator\Models\Creation\PendingChecker.cs:line 30
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
![94312426-281f-4901-96bf-45c92a7d21b5](https://user-images.githubusercontent.com/16854912/37861649-7429a88a-2f3e-11e8-8247-cc5b1726b686.png)

**Comment by ShuffleDATMT** [comment]
Still working on it

**Comment by Petterholm** [comment]
Any news? 
![4d1ca2ab-85b9-4a5a-bb72-dd7792022726](https://user-images.githubusercontent.com/16854912/37872784-daeb3b80-300e-11e8-84d3-84c6aa7742bd.png)

**Comment by ShuffleDATMT** [comment]
Memory leak, duplicated problem
